services:
    behappy_shipping_rates.shipping_calculator.weight_range:
        class: BeHappy\SyliusShippingRatesPlugin\Shipping\Calculator\WeightRangeCalculator
        public: true
        tags:
            -
                name: sylius.shipping_calculator
                calculator: weight_range
                label: behappy_shipping_rates.form.shipping_calculator.weight_range.label
                form_type: BeHappy\SyliusShippingRatesPlugin\Form\Type\Shipping\Calculator\ChannelBasedRangeConfigurationType

    behappy_shipping_rates.shipping_calculator.price_range:
        class: BeHappy\SyliusShippingRatesPlugin\Shipping\Calculator\PriceRangeCalculator
        public: true
        tags:
            -
                name: sylius.shipping_calculator
                calculator: price_range
                label: behappy_shipping_rates.form.shipping_calculator.price_range.label
                form_type: BeHappy\SyliusShippingRatesPlugin\Form\Type\Shipping\Calculator\ChannelBasedRangeConfigurationType

    behappy_shipping_rates.shipping_calculator.price_percent:
        class: BeHappy\SyliusShippingRatesPlugin\Shipping\Calculator\PricePercentCalculator
        public: true
        tags:
            -
                name: sylius.shipping_calculator
                calculator: price_percent
                label: behappy_shipping_rates.form.shipping_calculator.price_percent.label
                form_type: BeHappy\SyliusShippingRatesPlugin\Form\Type\Shipping\Calculator\ChannelBasedPricePercentConfigurationType

    behappy_shipping_rates.form.type.shipping_calculator.range:
        class: BeHappy\SyliusShippingRatesPlugin\Form\Type\Shipping\Calculator\RangeConfigurationType
        public: true
        arguments:
            - '@behappy_shipping_rates.form.type.range'
        tags:
            - { name: form.type }

    behappy_shipping_rates.form.type.range:
        class: BeHappy\SyliusShippingRatesPlugin\Form\Type\Shipping\RangeType
        public: true
        tags:
            - { name: form.type }

    behappy_shipping_rates.form.type.shipping_calculator.price_percent:
        class: BeHappy\SyliusShippingRatesPlugin\Form\Type\Shipping\Calculator\ChannelBasedPricePercentConfigurationType
        public: true
        tags:
            - { name: form.type}
